version: 2
jobs:
  build:
    docker:
      - image: yarnpkg/node-yarn
    working_directory: ~/zanatta
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: NPM Test
          command: npm test